name    'forward3ddev-r'
version '0.0.2'
source 'UNKNOWN'
author 'forward3d'
license 'Apache License, Version 2.0'
summary 'Install and manage R and its packages'
description 'Install and manage R; provides a defined type to install packages'
project_page 'https://github.com/forward3d/puppet-r'
